### ISSUE TITLE
Successfully satisfying the channel parameter

### ISSUE THREAD

**Issue by anoduck** [SiAsp/Telegram-Media-Downloader#1]
I see that you have used telethon as your means to communicate with telegram, so I assume that you want the name of the channel rather than the chatID for the channel. Regardless of which, the script fails to find the channel. I imagine the script is still in the early development stages and not fully functional.

**Comment by SiAsp** [comment]
The script will most likely be in an eternal-development stage, as it really just was meant to save me some time. Regardless it should be fully functional, either using the "share link" (t.me/<channel_name>) or just the name. But the name is still just the share link without "t.me/".

**Comment by anoduck** [comment]
That works for me, I am using it for the exact same reasons, that is to save time. I just needed that clarified.
